repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-merge-conflict
  - id: check-yaml
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: fix-encoding-pragma
    args: [--remove]
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: trailing-whitespace


- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.15.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.1
  hooks:
    - id: ruff
      types_or: [python, pyi, jupyter]
      args: [--fix]
    - id: ruff-format
      types_or: [python, pyi, jupyter]
