version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: '3.11'
  jobs:
    post_create_environment:
    - python -m pip install --no-cache-dir .[docs]
    - python -m pip install --exists-action=w --no-cache-dir -r docs/requirements.txt
